/**
 * Generator
 * ---------
 * Deterministic artifact generation from a validated IR.
 * The LLM never touches this layer — everything is driven by the schema
 * and registry (Step 5 of the spec).
 *
 * Produces three Accord Project artifacts:
 *   1. model.cto          — Concerto data model
 *   2. grammar.tem.md     — TemplateMark grammar with variable bindings
 *   3. logic.ergo         — Ergo logic stubs from approved rule templates
 */

import { getContractType } from "../registry/contractTypes.js";
import type { IR } from "../ir/types.js";
import { resolveValue, isAmbiguous } from "../ir/types.js";

export interface GeneratedArtifacts {
  /** Concerto .cto model file content */
  modelCto: string;
  /** TemplateMark grammar file content */
  grammarTemMd: string;
  /** Ergo logic stub file content */
  logicErgo: string;
  /** Template metadata (package.json equivalent) */
  packageJson: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. Concerto model generation
// ─────────────────────────────────────────────────────────────────────────────

const CONCERTO_TYPE_MAP: Record<string, string> = {
  String: "String",
  Double: "Double",
  Integer: "Integer",
  DateTime: "DateTime",
  Boolean: "Boolean",
  Duration: "Duration",
};

export function generateModelCto(ir: IR): string {
  const entry = getContractType(ir.contractType);
  const { schema } = entry;

  const lines: string[] = [
    `/*`,
    ` * Generated by Accord Pipeline — DO NOT EDIT`,
    ` * Contract type : ${ir.contractType}`,
    ` * Generated at  : ${new Date().toISOString()}`,
    ` */`,
    ``,
    `namespace ${schema.namespace}`,
    ``,
    `import org.accordproject.cicero.contract.* from https://models.accordproject.org/cicero/contract.cto`,
    `import org.accordproject.time.* from https://models.accordproject.org/time.cto`,
    ``,
    `concept ${schema.conceptName} extends AccordContract {`,
  ];

  for (const [fieldName, fieldSchema] of Object.entries(schema.fields)) {
    const concertoType = CONCERTO_TYPE_MAP[fieldSchema.type] ?? "String";
    const optional = fieldSchema.required ? "" : " optional";
    const comment = `  /** ${fieldSchema.description} */`;
    const declaration = `  o ${concertoType} ${fieldName}${optional}`;
    lines.push(comment, declaration);
  }

  lines.push(`}`);

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. TemplateMark grammar generation
// ─────────────────────────────────────────────────────────────────────────────

function formatFieldValue(value: unknown, type: string): string {
  if (value === null || value === undefined) return "[MISSING]";
  if (type === "DateTime") {
    try {
      return new Date(value as string).toLocaleDateString("en-US", {
        day: "numeric",
        month: "long",
        year: "numeric",
      });
    } catch {
      return String(value);
    }
  }
  return String(value);
}

export function generateGrammarTemMd(ir: IR): string {
  const entry = getContractType(ir.contractType);
  const { schema, templateRules } = entry;

  const lines: string[] = [
    `---`,
    `# ${ir.contractType} — Generated Template`,
    `*Generated by Accord Pipeline on ${new Date().toISOString()}*`,
    ``,
    `---`,
    ``,
    `## Contract Details`,
    ``,
  ];

  for (const [fieldName, fieldSchema] of Object.entries(schema.fields)) {
    const rule = templateRules[fieldName];
    if (!rule) continue;

    const rawValue = ir.fields[fieldName];
    const resolvedValue = rawValue !== undefined ? resolveValue(rawValue) : null;
    const ambiguous = rawValue !== undefined && isAmbiguous(rawValue);

    const rendered = formatFieldValue(resolvedValue, fieldSchema.type);
    const binding = rule.binding;
    const ambiguityFlag = ambiguous ? " ⚠️" : "";

    lines.push(`**${rule.label}**: ${binding}${ambiguityFlag}`);
    lines.push(`*Current value: ${rendered}*`);
    lines.push(``);
  }

  lines.push(
    `---`,
    ``,
    `## Clause Text`,
    ``
  );

  // Generate human-readable clause from contract type
  lines.push(...generateClauseText(ir));

  return lines.join("\n");
}

function generateClauseText(ir: IR): string[] {
  const entry = getContractType(ir.contractType);
  const f = ir.fields;
  const r = (k: string) => resolveValue(f[k]) ?? "[MISSING]";

  switch (ir.contractType) {
    case "DeliveryPayment":
      return [
        `{{seller}} ("Seller") agrees to deliver {{deliveryItem}} to {{buyer}} ("Buyer")`,
        `{{#if deliveryLocation}}at {{deliveryLocation}}{{/if}}`,
        `by {{deliveryDate as "D MMMM YYYY"}} ("Delivery Date").`,
        ``,
        `In consideration of such delivery, Buyer shall pay Seller {{currency}} {{paymentAmount}}`,
        `within {{paymentDueDays}} days following the Delivery Date.`,
      ];

    case "ServiceAgreement":
      return [
        `{{serviceProvider}} ("Service Provider") agrees to provide the following services`,
        `to {{client}} ("Client"): {{serviceDescription}}.`,
        ``,
        `Services shall commence on {{startDate as "D MMMM YYYY"}}`,
        `{{#if endDate}}and conclude on {{endDate as "D MMMM YYYY"}}{{/if}}.`,
        ``,
        `{{#if fixedFee}}The total fixed fee shall be {{currency}} {{fixedFee}}.{{/if}}`,
        `{{#if ratePerHour}}Services shall be billed at {{currency}} {{ratePerHour}} per hour.{{/if}}`,
        `Payment shall be made on a {{paymentFrequency}} basis.`,
        ``,
        `{{#if governingLaw}}This agreement is governed by the laws of {{governingLaw}}.{{/if}}`,
      ];

    case "LatePenalty":
      return [
        `If {{obligorParty}} ("Obligor") fails to fulfill its {{obligationType}} obligation`,
        `to {{obligeeParty}} ("Obligee") on the agreed date,`,
        `a grace period of {{gracePeriodDays}} calendar days shall apply.`,
        ``,
        `Following the grace period, a late penalty of {{penaltyRatePercent}}%`,
        `{{penaltyPeriod}} shall accrue on the outstanding amount.`,
        ``,
        `{{#if maxPenaltyPercent}}`,
        `The total penalty shall not exceed {{maxPenaltyPercent}}% of the original obligation.`,
        `{{/if}}`,
      ];

    default:
      return [`[Clause text not defined for contract type: ${ir.contractType}]`];
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. Ergo logic generation (stub from approved templates)
// ─────────────────────────────────────────────────────────────────────────────

export function generateLogicErgo(ir: IR): string {
  const entry = getContractType(ir.contractType);
  const { schema } = entry;

  const lines: string[] = [
    `/*`,
    ` * Generated Ergo Logic — DO NOT EDIT`,
    ` * Contract type : ${ir.contractType}`,
    ` * Namespace     : ${schema.namespace}`,
    ` * Generated at  : ${new Date().toISOString()}`,
    ` */`,
    ``,
    `namespace ${schema.namespace}`,
    ``,
    `import org.accordproject.cicero.runtime.*`,
    `import org.accordproject.time.*`,
    ``,
  ];

  switch (ir.contractType) {
    case "DeliveryPayment":
      lines.push(
        `define function isDeliveryLate(deliveryDate: DateTime) : Boolean {`,
        `  return momentIsAfter(now(), deliveryDate)`,
        `}`,
        ``,
        `contract DeliveryPayment over DeliveryPaymentContract {`,
        `  clause payment(request: Request): Response {`,
        `    enforce isDeliveryLate(contract.deliveryDate) = false`,
        `      else throw ErgoErrorResponse{ message: "Delivery date has passed" };`,
        `    return Response{}`,
        `  }`,
        `}`
      );
      break;

    case "ServiceAgreement":
      lines.push(
        `define function isServiceActive(startDate: DateTime, endDate: DateTime?) : Boolean {`,
        `  return momentIsAfter(now(), startDate) and`,
        `    (endDate = none or momentIsBefore(now(), endDate??))`,
        `}`,
        ``,
        `contract ServiceAgreement over ServiceAgreementContract {`,
        `  clause invoiceService(request: Request): Response {`,
        `    enforce isServiceActive(contract.startDate, contract.endDate)`,
        `      else throw ErgoErrorResponse{ message: "Service period is not active" };`,
        `    return Response{}`,
        `  }`,
        `}`
      );
      break;

    case "LatePenalty":
      lines.push(
        `define function computePenalty(`,
        `  baseAmount: Double,`,
        `  daysLate: Integer,`,
        `  gracePeriodDays: Integer,`,
        `  penaltyRatePercent: Double,`,
        `  maxPenaltyPercent: Double?`,
        `) : Double {`,
        `  let effectiveDaysLate = daysLate - gracePeriodDays;`,
        `  enforce effectiveDaysLate > 0 else return 0.0;`,
        `  let rawPenalty = baseAmount * (penaltyRatePercent / 100.0) * integerToDouble(effectiveDaysLate);`,
        `  match maxPenaltyPercent`,
        `    with let? cap then min(rawPenalty, baseAmount * (cap / 100.0))`,
        `    else rawPenalty`,
        `}`,
        ``,
        `contract LatePenalty over LatePenaltyContract {`,
        `  clause applyPenalty(request: PenaltyRequest): PenaltyResponse {`,
        `    let penaltyAmount = computePenalty(`,
        `      request.baseAmount,`,
        `      request.daysLate,`,
        `      contract.gracePeriodDays,`,
        `      contract.penaltyRatePercent,`,
        `      contract.maxPenaltyPercent`,
        `    );`,
        `    return PenaltyResponse{ penalty: penaltyAmount }`,
        `  }`,
        `}`
      );
      break;

    default:
      lines.push(`/* No logic template available for ${ir.contractType} */`);
  }

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. Package metadata
// ─────────────────────────────────────────────────────────────────────────────

export function generatePackageJson(ir: IR): string {
  const entry = getContractType(ir.contractType);
  const pkg = {
    name: `${ir.contractType.toLowerCase()}-template`,
    displayName: `${ir.contractType} Template`,
    description: entry.schema.description,
    version: "1.0.0",
    accordproject: {
      template: "contract",
      cicero: "^0.20.0",
      runtime: "ergo",
      contractName: entry.schema.conceptName,
      namespace: entry.schema.namespace,
    },
    keywords: ["accordproject", "cicero", "template", ir.contractType.toLowerCase()],
    author: "Generated by Accord Pipeline",
    license: "Apache-2.0",
  };

  return JSON.stringify(pkg, null, 2);
}

// ─────────────────────────────────────────────────────────────────────────────
// Main entry point
// ─────────────────────────────────────────────────────────────────────────────

export function generateArtifacts(ir: IR): GeneratedArtifacts {
  return {
    modelCto: generateModelCto(ir),
    grammarTemMd: generateGrammarTemMd(ir),
    logicErgo: generateLogicErgo(ir),
    packageJson: generatePackageJson(ir),
  };
}
